name: Build and Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      REGISTRY_HOST: quay.io
      DOCKER_PREFIX: shawnlu0127
      BUILD_ARCH: arm64
    steps:
    - uses: actions/checkout@v3

    - name: Set current date as tag
      run: echo "DOCKER_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: shawnlu0127
        password: ${{ secrets.QUAY }}

    - name: Build
      run: make -j 2

    - name: Push
      run: make push

    - name: Manifest
      run: make manifests

    - name: Gzip yaml
      run: tar zcvf manifests.tgz manifests

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GIT_TOKEN }}
        file: manifests.tgz
        asset_name: manifest
        tag: ${{ github.ref }}
        overwrite: true
        body: "kubevirt yaml manifests"
