name: Build and Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      REGISTRY_HOST: quay.io
      DOCKER_PREFIX: lucheng0127
      BUILD_ARCH: arm64
      DOCKER_TAG: ${{ steps.date.outputs.date }}
    steps:
    - uses: actions/checkout@v3

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: lucheng0127
        password: ${{ secrets.QUAY }}

    - name: Build
      run: make

    - name: Push
      run: make push
